In [13]:
import numpy as np
import argparse
import cv2
import os

In [30]:
original =  cv2.imread('C:\\Users\Cheon\MasterData\mLTurn\sa175.png'
                 );

In [31]:
original

array([[[146, 142, 138],
        [147, 143, 139],
        [151, 147, 143],
        ...,
        [142, 140, 136],
        [141, 139, 135],
        [141, 139, 135]],

       [[147, 143, 139],
        [148, 144, 140],
        [149, 145, 141],
        ...,
        [141, 139, 135],
        [140, 138, 134],
        [140, 138, 134]],

       [[150, 146, 142],
        [149, 145, 141],
        [148, 144, 140],
        ...,
        [142, 140, 136],
        [141, 139, 135],
        [141, 139, 135]],

       ...,

       [[124, 122, 118],
        [123, 121, 117],
        [124, 122, 118],
        ...,
        [104, 102,  98],
        [104, 102,  98],
        [100,  98,  94]],

       [[121, 119, 115],
        [121, 119, 115],
        [121, 119, 115],
        ...,
        [104, 102,  98],
        [104, 102,  98],
        [100,  98,  94]],

       [[121, 119, 115],
        [121, 119, 115],
        [120, 118, 114],
        ...,
        [103, 101,  97],
        [104, 102,  98],
        [100,  98,  94]]

In [4]:
cv2.imshow('color image',original) 
cv2.waitKey(0); cv2.destroyAllWindows(); cv2.waitKey(1)

-1

In [5]:
width = 512
height = 512
dim = (width, height)
 
# resize image
resized = cv2.resize(original, dim, interpolation = cv2.INTER_AREA)
 
print('Resized Dimensions : ',resized.shape)
 
cv2.imshow("Resized image", resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

Resized Dimensions :  (512, 512, 3)


In [6]:
# define the upper and lower boundaries of the HSV pixel
# intensities to be considered 'skin'
lower = np.array([30, 30, 20], dtype = "uint8")
upper = np.array([120, 255, 200], dtype = "uint8")

In [9]:
converted = cv2.cvtColor(resized, cv2.COLOR_RGB2HSV)
skinMask = cv2.inRange(converted, lower, upper)
skinMask

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [10]:
# apply a series of erosions and dilations to the mask
# using an elliptical kernel
kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (10, 10))
skinMask = cv2.erode(skinMask, kernel, iterations = 1)
skinMask = cv2.dilate(skinMask, kernel, iterations = 2)

# show the skin in the image along with the mask
cv2.imshow("Mask image", skinMask)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [89]:
import numpy as np
import argparse
import cv2


def massconvert(filedir):
    original =  cv2.imread(filedir);


    width = 512
    height = 512
    dim = (width, height)

    # resize image
    resized = cv2.resize(original, dim, interpolation = cv2.INTER_AREA)


    # define the upper and lower boundaries of the HSV pixel
    # intensities to be considered 'skin'
    lower = np.array([30, 30, 20], dtype = "uint8")
    upper = np.array([120, 255, 200], dtype = "uint8")

    converted = cv2.cvtColor(resized, cv2.COLOR_RGB2HSV)
    skinMask = cv2.inRange(converted, lower, upper)

    # apply a series of erosions and dilations to the mask
    # using an elliptical kernel
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (10, 10))
    skinMask = cv2.erode(skinMask, kernel, iterations = 1)
    skinMask = cv2.dilate(skinMask, kernel, iterations = 2)
    print(filedir)




In [90]:
import os, re
for root, subdirectories, files in os.walk(directory):
    for subdirectory in subdirectories:
        mainDir = 'C:\\Users\Cheon\MasterData\\' 
        pfName = mainDir + subdirectory
        for i in os.listdir('C:\\Users\Cheon\MasterData\mLTurn'):
            #print(os.path.join(pfName,i))
            if os.path.isfile(os.path.join(pfName,i)) and i.startswith('sa'):
                massconvert(os.path.join(pfName,i))
                #print(os.path.join(pfName,i))

[[[153 147 141]
  [154 148 142]
  [155 149 143]
  ...
  [147 143 137]
  [148 144 138]
  [149 145 139]]

 [[154 148 142]
  [152 146 140]
  [154 148 142]
  ...
  [148 144 138]
  [149 145 139]
  [149 145 139]]

 [[155 149 143]
  [154 148 142]
  [153 147 141]
  ...
  [147 143 137]
  [147 143 137]
  [147 143 137]]

 ...

 [[153 149 143]
  [154 150 144]
  [152 148 142]
  ...
  [118 116 109]
  [116 115 106]
  [117 116 107]]

 [[152 148 142]
  [153 149 143]
  [152 148 142]
  ...
  [117 115 109]
  [115 114 105]
  [116 115 106]]

 [[152 148 142]
  [153 149 143]
  [152 148 142]
  ...
  [114 112 106]
  [116 113 104]
  [116 113 104]]]
[[[154 148 142]
  [154 148 142]
  [155 149 143]
  ...
  [152 148 142]
  [149 145 139]
  [148 144 138]]

 [[153 147 141]
  [154 148 142]
  [154 148 142]
  ...
  [150 146 140]
  [148 144 138]
  [148 144 138]]

 [[154 148 142]
  [153 147 141]
  [154 148 142]
  ...
  [149 145 139]
  [148 144 138]
  [148 144 138]]

 ...

 [[154 149 140]
  [155 150 141]
  [155 150 141]
  ..

[[[148 146 142]
  [148 146 142]
  [148 146 142]
  ...
  [146 142 138]
  [146 142 138]
  [147 143 139]]

 [[148 146 142]
  [151 149 145]
  [152 150 146]
  ...
  [147 143 139]
  [147 143 139]
  [146 142 138]]

 [[149 147 143]
  [148 146 142]
  [152 150 146]
  ...
  [145 141 137]
  [147 143 139]
  [147 143 139]]

 ...

 [[123 120 118]
  [122 119 115]
  [123 120 116]
  ...
  [101  98  97]
  [102  99  98]
  [102  99  98]]

 [[119 117 114]
  [120 118 114]
  [122 118 114]
  ...
  [100  97  96]
  [100  97  96]
  [101  98  97]]

 [[119 116 114]
  [123 120 116]
  [124 121 117]
  ...
  [101  98  97]
  [ 98  95  94]
  [101  98  97]]]
[[[150 148 144]
  [150 148 144]
  [149 147 143]
  ...
  [147 143 137]
  [145 141 135]
  [145 141 135]]

 [[149 147 143]
  [149 147 143]
  [150 148 144]
  ...
  [147 143 137]
  [147 143 137]
  [147 143 137]]

 [[150 148 144]
  [152 150 146]
  [153 151 147]
  ...
  [147 143 137]
  [146 142 136]
  [147 143 137]]

 ...

 [[125 123 119]
  [121 119 115]
  [121 119 115]
  ..

[[[150 148 144]
  [148 146 142]
  [153 151 147]
  ...
  [144 142 138]
  [145 143 139]
  [146 144 140]]

 [[151 149 145]
  [150 148 144]
  [150 148 144]
  ...
  [145 143 139]
  [145 143 139]
  [147 145 141]]

 [[153 151 147]
  [149 147 143]
  [148 146 142]
  ...
  [147 145 141]
  [148 146 142]
  [148 146 142]]

 ...

 [[128 124 120]
  [131 127 123]
  [133 129 125]
  ...
  [ 97  95  93]
  [ 99  95  94]
  [ 99  94  93]]

 [[129 125 121]
  [131 127 123]
  [132 128 124]
  ...
  [ 96  94  93]
  [ 98  94  93]
  [100  95  94]]

 [[128 124 120]
  [131 127 123]
  [128 124 120]
  ...
  [ 92  90  89]
  [ 96  91  90]
  [ 97  92  91]]]
[[[152 150 146]
  [148 146 142]
  [152 150 146]
  ...
  [146 144 140]
  [144 142 138]
  [146 144 140]]

 [[153 151 147]
  [150 148 144]
  [148 146 142]
  ...
  [146 144 140]
  [148 146 142]
  [149 147 143]]

 [[153 151 147]
  [149 147 143]
  [147 145 141]
  ...
  [147 145 141]
  [149 147 143]
  [150 148 144]]

 ...

 [[128 124 120]
  [130 126 122]
  [133 129 125]
  ..

In [43]:
for root, subdirectories, files in os.walk(directory):
    for subdirectory in subdirectories:
        print(subdirectory)

mClose
mLForward
mLTurn
mLUp
mNeutral
mPointIn
mPointOut
mRForward
mRTurn
mRUp


In [ ]:
    
    # Save the thumbnail as "(original_name)_thumb.png"
    image.save(name + '_thumb.png')